apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 
etcd:
  endpoints:
    - https://<etcd0-ip-address>:2379
    - https://<etcd1-ip-address>:2379
    - https://<etcd2-ip-address>:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd_client.pem
  keyFile: /etc/kubernetes/pki/etcd_client-key.pem
networking:
  podSubnet: 10.90.0.0/16
apiServerCertSANs:
  - <load-balancer-ip>
apiServerExtraArgs:
  endpoint-reconciler-type: lease
